[package]
name = "rengrave-ui"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[[bin]]
name = "rengrave-ui"
path = "src/main.rs"

[dependencies]
eframe.workspace = true
egui.workspace = true
image.workspace = true
rengrave-core = { path = "../rengrave-core" }
rfd.workspace = true
ttf-parser.workspace = true
