use std::path::PathBuf;

use crate::project::{DocumentError, DocumentRequest, load_document};
use crate::settings::LegacySettings;
use crate::{FENGRAVE_VERSION, RENGRAVE_VERSION};

#[derive(Debug, Clone, Default, PartialEq, Eq)]
pub struct BatchRequest {
    pub batch: bool,
    pub gcode_file: Option<PathBuf>,
    pub font_or_image: Option<PathBuf>,
    pub default_dir: Option<PathBuf>,
    pub text: Option<String>,
    pub output: Option<PathBuf>,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct BatchOutput {
    pub gcode: String,
    pub warnings: Vec<String>,
}

#[derive(Debug, thiserror::Error)]
pub enum BatchError {
    #[error(transparent)]
    Document(#[from] DocumentError),
}

pub fn prepare_batch_output(request: &BatchRequest) -> Result<BatchOutput, BatchError> {
    let document = load_document(&DocumentRequest {
        gcode_file: request.gcode_file.clone(),
        font_or_image: request.font_or_image.clone(),
        default_dir: request.default_dir.clone(),
        text: request.text.clone(),
    })?;

    let mut warnings = document.warnings;
    warnings.push(
        "toolpath generation is not ported yet; output contains compatible settings comments only"
            .to_owned(),
    );

    Ok(BatchOutput {
        gcode: render_settings_only_gcode(&document.settings, &document.text),
        warnings,
    })
}

fn render_settings_only_gcode(settings: &LegacySettings, text: &str) -> String {
    let mut lines = vec![
        format!("( Code generated by r-engrave-{RENGRAVE_VERSION} )"),
        format!("( Compatibility target: f-engrave-{FENGRAVE_VERSION}.py )"),
        "(Settings used in f-engrave when this file was created)".to_owned(),
        format!("(Engrave Text:{} )", sanitized_text_comment(text)),
        "(=========================================================)".to_owned(),
    ];

    lines.extend(settings.to_comments());
    lines.push("(#########################################################)".to_owned());
    lines.push("( R-Engrave scaffold: toolpath generation is not implemented yet )".to_owned());
    lines.push(String::new());
    lines.join("\n")
}

fn sanitized_text_comment(text: &str) -> String {
    let mut output = String::new();
    for ch in text.chars().take(40) {
        if ch.is_ascii_alphanumeric() {
            output.push(ch);
        } else {
            output.push(' ');
        }
    }
    if text.chars().count() > 40 {
        output.push_str("___");
    }
    output
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn batch_text_uses_legacy_pipe_newline_convention() {
        let output = prepare_batch_output(&BatchRequest {
            batch: true,
            text: Some("Line 1|Line 2".to_owned()),
            ..BatchRequest::default()
        })
        .unwrap();

        assert!(
            output.gcode.contains(
                "(fengrave_set TCODE       076 105 110 101 032 049 010 076 105 110 101 )"
            )
        );
        assert!(output.gcode.contains("(fengrave_set TCODE       032 050 )"));
    }

    #[test]
    fn font_path_updates_text_input_settings() {
        let output = prepare_batch_output(&BatchRequest {
            batch: true,
            font_or_image: Some(PathBuf::from("/tmp/example.ttf")),
            ..BatchRequest::default()
        })
        .unwrap();

        assert!(
            output
                .gcode
                .contains("(fengrave_set fontfile    \"example.ttf\" )")
        );
        assert!(output.gcode.contains("(fengrave_set input_type  text )"));
    }
}
