pub mod batch;
pub mod bitmap;
pub mod cleanup;
pub mod design;
pub mod dxf;
pub mod export;
pub mod external;
pub mod font;
pub mod gcode;
pub mod general_profile;
pub mod general_toolbit;
pub mod geometry;
pub mod layout;
pub mod profile;
pub mod project;
pub mod settings;
pub mod svg;
pub mod toolbit;
pub mod vcarve;

pub const FENGRAVE_VERSION: &str = "1.78";
pub const RENGRAVE_VERSION: &str = env!("CARGO_PKG_VERSION");
